### ISSUE TITLE
Move to Parcel

### ISSUE THREAD

**Issue by jhpratt** [r-spacex/Enceladus-LTI#3]
Parcel is a bundler that can, at least in this instance, replace my entire build script. For basic situations, it works great, reducing my workload and increasing build speed. Unfortunately, for larger projects, it's currently incapable of handling small things like CSS being split across multiple files.

Blocking:

- [ ] CSS importing is effectively broken (parcel-bundler/parcel#1165, parcel-bundler/parcel#329) — possibly fixed by parcel-bundler/parcel#2157?

Nice to have:

- [ ] Inline CSS in JavaScript — reduces HTTP overhead with custom elements (parcel-bundler/parcel#1370)
  Re-filed an issue with parcel-bundler/parcel#2864, as the previous was closed without resolution.
- [ ] Subresource integrity (parcel-bundler/parcel#2003)
- [ ] Basic PWA support (parcel-bundler/parcel#301) — This one will be a ways off for Enceladus no matter what.
- [ ] Exclude helper methods if not necessary (parcel-bundler/parcel#2566)

[Parcel 2 is almost ready for alpha](https://github.com/parcel-bundler/parcel/issues/2659#issuecomment-470511508), so I may play around a bit when that's the case to see what issues are blocking and/or nice to have.

**Comment by jhpratt** [comment]
Going to attempt to work around the CSS import bug. I think it'll be worth it, as tooling will be a very large part of the dual-builds of client and host.

**Comment by jhpratt** [comment]
Abandoning this for the time being. After recently putting Rollup into the mix, code splitting is automated and transformed CSS is included in JavaScript. There's also zero overhead versus what I would do by hand.

If there's some reason to still switch to Parcel, I'm certainly down to hear. Until that time, the config isn't terrible.
